"""answer_questions

Revision ID: 4cbacb9c74d5
Revises: 37e0bb6cb2df
Create Date: 2020-08-21 15:07:58.813692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbacb9c74d5'
down_revision = '37e0bb6cb2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('answers_questions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'answers_questions')
    # ### end Alembic commands ###
