"""add answer comments

Revision ID: 8cdcd21f2511
Revises: e909bdf554e1
Create Date: 2020-08-21 18:35:05.007075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdcd21f2511'
down_revision = 'e909bdf554e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('comments', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'comments')
    # ### end Alembic commands ###
