"""add answer value

Revision ID: e909bdf554e1
Revises: 4cbacb9c74d5
Create Date: 2020-08-21 16:32:16.753575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e909bdf554e1'
down_revision = '4cbacb9c74d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'value')
    # ### end Alembic commands ###
